LiniBelajar/LiniBelajar/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('ecommerce/', include('ecommerce_app.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('about/', TemplateView.as_view(template_name='about.html')),
    path('komunitas', include('community.urls'), name='community'),
    path('kelas-online/', include('online_class.urls'), name='online_class'),
    path('talkshow/', include('event.urls'), name='event'),
    path('', include('user.urls')),
    path('', include('testvue.urls')),
    path('api/posts/', include('postAPI.urls')),
    path('api/user/', include('userAPI.urls')),
    path('api/user/profile/', include('profileAPI.urls')),
    #path('komunitas/', include('community.urls'), name='community'),
    #path('komunitas/', include('community.urls')),
    path('react/', TemplateView.as_view(template_name='react.html')),
    path('quizs', include('quiz.urls'), name='quiz'),
    path('admin/', admin.site.urls),
    #path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

LiniBelajar/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

LiniBelajar/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('get_order_total/', views.getOrderTotal, name='get_order_total'),
    path('process_order/', views.processOrder, name='process_order'),
    path('show_detail/', views.showDetail, name='show_detail'),
    path('update_item/', views.updateItem, name='update_item'),
]
'''
path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
     path('register/', views.registerView, name='register'),
'''

LiniBelajar/store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, related_name = 'customer', null=True, on_delete=models.SET_NULL, blank=True)
    name = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["name"]

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, null=True)
    price = models.DecimalField(max_digits=12, decimal_places=0)
    description = models.TextField(
        default='No description', null=True, blank=True)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(upload_to='products/', null=True, blank=True)

    def __str__(self):
        return self.name

    @property  # decorator untuk membuat property sebuah class
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = 'https://via.placeholder.com/640x360.png'
        return url


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_order = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=255, null=True)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()

        for i in orderitems:
            if i.product.digital == False:
                shipping = True

        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_item(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    state = models.CharField(max_length=255, null=True)
    zipcode = models.CharField(max_length=255, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

LiniBelajar/store/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import Http404
from django.db.models import Q
import json
import datetime

from .models import *
from .utils import cookieCart, cartData, guestOrder, makePayment, productPaginator

# Create your views here.


def store(request):

    data = cartData(request)
    cartItems = data['cartItems']

    if request.GET.get('search'):
        search = request.GET.get('search')
        product_list = Product.objects.filter(name__icontains=search)
    else:
        product_list = Product.objects.all()
        search = False

    per_page = 9
    number_paginator = 2

    product_pagination = productPaginator(
        request, product_list, per_page, number_paginator)

    context = {
        'products': product_pagination['products'],
        'cartItems': cartItems,
        'start': product_pagination['start'],
        'end': product_pagination['end'],
        'page': product_pagination['page'],
        'show_page_num': range(product_pagination['start'], product_pagination['end']+1),
        'total_page': product_pagination['total_page'],
    }

    if search:
        context['search'] = search

    return render(request, 'store/store.html', context)

@login_required
def cart(request):

    data = cartData(request)
    order = data['order']
    items = data['items']
    cartItems = data['cartItems']

    context = {
        'items': items,
        'order': order,
        'cartItems': cartItems,
    }
    return render(request, 'store/cart.html', context)


def checkout(request):

    data = cartData(request)
    order = data['order']
    items = data['items']
    cartItems = data['cartItems']

    context = {
        'items': items,
        'order': order,
        'cartItems': cartItems,
    }
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(
        customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(
        order=order, product=product)

    if action == 'add':
        orderItem.quantity += 1
    elif action == 'remove':
        orderItem.quantity -= 1

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    try:
        quantity = orderItem.quantity
    except OrderItem.DoesNotExist:
        quantity = 0

    total_item = order.get_cart_item
    total_price = order.get_cart_total

    json_response = {
        'total_item': total_item,
        'quantity': quantity,
        'total': total_price,
        'item_price': orderItem.get_total
    }

    return JsonResponse(json_response, safe=False)


def processOrder(request):
    data = json.loads(request.body)
    transaction_id = datetime.datetime.now().timestamp()

    if request.method == 'POST':
        if request.user.is_authenticated:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(
                customer=customer, complete=False)
        else:
            customer, order = guestOrder(request, data)

        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == order.get_cart_total:
            order.complete = True

        order.save()

        if order.shipping == True:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],
                state=data['shipping']['state'],
                zipcode=data['shipping']['zipcode']
            )

        payment_data = {
            'order_id': order.transaction_id,
            'gross_amount': order.get_cart_total,
            'name': customer.name,
            'email': customer.email,
        }

        token = makePayment(request, payment_data)

    return JsonResponse({'token': token}, safe=False)

'''
def loginView(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        try:
            user = get_user_model().objects.get(email=email)
            username = user.username
        except:
            username = ''

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('store:store')
        else:
            messages.error(request, 'Login invalid')
            return redirect('store:store')


def registerView(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        name = request.POST['name']
        password = request.POST['password']

        user, created = get_user_model().objects.get_or_create(username=username)
        if created:
            user.email = email
            user.set_password(user.password)
            user.save()

        customer, created = Customer.objects.get_or_create(email=email)
        customer.name = name
        customer.user = user
        customer.save()

        login(request, user)

        return redirect('store:store')


def logoutView(request):
    logout(request)

    return redirect(('store:store'))
'''

def showDetail(request):
    product = Product.objects.get(id=request.GET.get('id'))

    product_json = serializers.serialize('python', [product])

    return JsonResponse(product_json, safe=False)


def getOrderTotal(request):
    data = json.loads(request.body)
    total_harga = 0
    total_item = 0

    for key, value in data.items():
        productId = int(key)
        harga_product = Product.objects.get(id=productId).price
        total_harga += (harga_product*value['quantity'])
        total_item += value['quantity']

    json_data = {
        'total_price': int(total_harga),
        'total_item': total_item,
    }

    return JsonResponse(json_data, safe=False)

LiniBelajar/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}


{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a href="{% url 'store:store' %}" class="btn btn-outline-dark">&#x2190; Continue Shoping</a>
            <br>
            <br>

            <table class="table">
                <tr>
                    <th>
                        <h5>Items: <strong id="items">{{order.get_cart_item}}</strong></h5>
                    </th>
                    <th>
                        <h5>Total: <strong id="total-price">Rp <script>
                                    rupiah('{{order.get_cart_total|floatformat:0}}')
                                </script></strong></h5>
                    </th>
                    <th>
                        <a href="{% url 'store:checkout' %}" class="btn btn-success float-right m-1">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>

        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row" data-product="{{item.product.id}}">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}" alt=""></div>
                <div style="flex:2">{{item.product.name}}</div>
                <div style="flex:1">Rp <script>
                        rupiah('{{item.product.price|floatformat:0}}')
                    </script>
                </div>
                <div style="flex:1">
                    <p class="quantity" data-product="{{item.product.id}}">{{item.quantity}}</p>
                    <div class="quantity">
                        <img class="chg-quantity update-cart" data-product="{{item.product.id}}" data-action="add"
                            data-url="{% url 'store:update_item' %}" data-urltotal="{% url 'store:get_order_total' %}"
                            style="margin: -2px 1px;" src="{% static 'img-store/up-arrow.png' %}" alt="">
                        <img class="chg-quantity update-cart" data-product="{{item.product.id}}" data-action="remove"
                            data-url="{% url 'store:update_item' %}" data-urltotal="{% url 'store:get_order_total' %}"
                            style="margin: -2px 1px;" src="{% static 'img-store/down-arrow.png' %}" alt="">
                    </div>
                </div>
                <div id="item-total" style="flex:1">Rp <script>
                        rupiah('{{item.get_total|floatformat:0}}')
                    </script>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock content %}

LiniBelajar/store/templates/store/checkout.html
{% extends 'store/main.html' %} {% load static %} {% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                {% csrf_token %}
                <div id="user-info">
                    <p>Customer Information:</p>
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name.." />
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email.." />
                    </div>
                </div>

                <div id="shipping-info" class="">
                    <hr />
                    <p>Shipping Information:</p>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address.." />
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City.." />
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State.." />
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code.." />
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="country" placeholder="Country.." />
                    </div>
                </div>
                <hr />
                <input type="submit" value="Continue" id="form-button" class="btn btn-success btn-block" />
            </form>
        </div>

        <br />
        <div class="box-element hidden" id="payment-info">
            <small>Payment Options</small>
            <button id="make-payment">Make Payment</button>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
            <hr />
            <h3>Order Summary</h3>
            <hr />

            {% for item in items %}
            <div class="cart-row">
                <div style="flex: 2">
                    <img class="row-image" src="{{item.product.imageURL}}" />
                </div>
                <div style="flex: 3">
                    <p>{{item.product.name}}</p>
                </div>
                <div style="flex: 2">
                    <p>Rp <script>
                            rupiah('{{item.product.price|floatformat:0}}')
                        </script>
                    </p>
                </div>
                <div style="flex: 1">
                    <p>x{{item.quantity}}</p>
                </div>
            </div>
            {% endfor %}

            <h5>Items: {{order.get_cart_item}}</h5>
            <h5>Total: Rp <script>
                    rupiah('{{order.get_cart_total|floatformat:0}}')
                </script>
            </h5>
        </div>
    </div>
</div>
{% endblock content %}


{% block script %}
<script>
    let shipping = "{{order.shipping}}";
    let total = '{{order.get_cart_total}}';

    if (shipping == "False") {
        document.getElementById("shipping-info").classList.add("hidden");
    }

    if (user != "AnonymousUser") {
        document.getElementById('user-info').innerHTML = '';
    }

    if (shipping == 'False' && user != 'AnonymousUser') {
        document.getElementById('form-wrapper').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden');
    }

    let form = document.getElementById("form");
    var csrftoken = document.getElementsByTagName('input')[0].value;

    form.addEventListener("submit", function (e) {
        e.preventDefault();

        document.getElementById("form-button").classList.add("hidden");
        document.getElementById("payment-info").classList.remove("hidden");
    });

    document.getElementById("make-payment").addEventListener("click", function () {
        submitFormData();
    });

    function submitFormData() {
        let userFormData = {
            'name': null,
            'email': null,
            'total': total,
        }

        let shippingInfo = {
            'address': null,
            'city': null,
            'state': null,
            'zipcode': null,
        }

        if (shipping != 'False') {
            shippingInfo.address = form.address.value;
            shippingInfo.city = form.city.value;
            shippingInfo.state = form.state.value;
            shippingInfo.zipcode = form.zipcode.value;
        }

        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value;
            userFormData.email = form.email.value;
        }

        url = "{% url 'store:process_order' %}";

        fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({
                    'form': userFormData,
                    'shipping': shippingInfo,
                })
            })
            .then((response) => response.json())
            .then((data) => {
                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/';

                console.log(data.token);

                snap.pay(data.token, {
                    onSuccess: function (result) {
                        /* You may add your own implementation here */
                        alert("payment success!");
                        location.href = '{% url "store:store" %}';
                    },
                    onPending: function (result) {
                        /* You may add your own implementation here */
                        alert("wating your payment!");
                        console.log(result);
                    },
                    onError: function (result) {
                        /* You may add your own implementation here */
                        alert("payment failed!");
                        console.log(result);
                    },
                    onClose: function () {
                        /* You may add your own implementation here */
                        alert('you closed the popup without finishing the payment');
                    }
                });
            });
    }
</script>
{% endblock script %}

LiniBelajar/store/templates/store/store.html
{% extends 'store/main.html' %} {% load static %} {% block content %}
<div class="text-center my-4 overflow-auto pt-2 px-4 search-wrapper">
    <form class="overflow-auto p-0 form-search" method="GET" action="">
        <input name="search" style="display: inline-block"
            class="form-control rounded-0 float-left ml-5 mr-0 col-lg-10 border-info search"
            aria-describedby="button-addon2" type="text" placeholder="What are you looking for?" />
        <button class="btn btn-outline-info ml-0 float-left btn-search" type="submit" id="button-addon2">
            Search
        </button>
    </form>
</div>

<div class="alert alert-success px-2 py-0 mt-0 mb-0 mr-auto hidden text-center" id="cart-alert" role="alert">
    Succes add item to cart!
</div>

{% if messages %} {% for message in messages %}
<div class="alert alert-danger px-2 py-0 mt-0 mb-0 mr-auto text-center" id="cart-alert" role="alert">
    {{message}}
</div>
{% endfor %} {% endif %}

<div class="row">
    {% for product in products %}
    <div class="col-lg-4">
        <!-- <img class="thumbnail" src="https://via.placeholder.com/640x360.png" alt=""> -->
        <img class="thumbnail img-fluid w-100" src="{{ product.imageURL }}" alt="" />
        <div class="box-element product">
            <h6><strong>{{ product.name|truncatechars:20 }}</strong></h6>
            <hr />
            <button class="btn btn-outline-secondary add-btn update-cart" data-product="{{product.id}}"
                data-action="add" data-url="{% url 'store:update_item' %}">
                Add to Cart
            </button>
            <button type="button" class="btn btn-outline-success btn-detail" data-url="{% url 'store:show_detail' %}"
                data-product="{{product.id}}" data-toggle="modal" data-target="#detailModal">
                View
            </button>
            <h5 class="d-inline float-right">
                Rp
                <script>
                    rupiah("{{ product.price|floatformat:0 }}");
                </script>
            </h5>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Pagination -->
<div class="row my-4">
    <div class="col-lg-12 d-flex">
        <div class="mx-auto">
            {% if search %}
            <ul class="pagination">
                <!-- non-search-pagination -->
                {% if page == 1 %}
                <li class="page-item disabled">
                    <a class="page-link" href="">First</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'store:store' %}?page=1&search={{search}}">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                        href="{% url 'store:store' %}?page={{products.previous_page_number}}&search={{search}}">&laquo;</a>
                </li>
                {% endif %}

                <!-- number-pagination -->

                {% for i in show_page_num %} {% if page == i %}
                <li class="page-item active">
                    <a class="page-link" href="{% url 'store:store' %}?page={{i}}&search={{search}}">{{i}}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'store:store' %}?page={{i}}&search={{search}}">{{i}}</a>
                </li>
                {% endif %} {% endfor %}

                <!-- search-pagination (Last and Next)-->

                {% if page == products.paginator.num_pages %}
                <li class="page-item disabled">
                    <a class="page-link" href="">&laquo;</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="">Last</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link"
                        href="{% url 'store:store' %}?page={{products.next_page_number}}&search={{search}}">&raquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                        href="{% url 'store:store' %}?page={{products.paginator.num_pages}}&search={{search}}">Last</a>
                </li>
                {% endif %}
            </ul>

            {% else %}

            <ul class="pagination">
                <!-- non-search-pagination -->
                {% if page == 1 %}
                <li class="page-item disabled">
                    <a class="page-link" href="">First</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'store:store' %}?page=1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                        href="{% url 'store:store' %}?page={{products.previous_page_number}}">&laquo;</a>
                </li>
                {% endif %}

                <!-- number-pagination -->

                {% for i in show_page_num %} {% if page == i %}
                <li class="page-item active">
                    <a class="page-link" href="{% url 'store:store' %}?page={{i}}">{{i}}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'store:store' %}?page={{i}}">{{i}}</a>
                </li>
                {% endif %} {% endfor %}

                <!-- search-pagination (Last and Next)-->

                {% if page == products.paginator.num_pages %}
                <li class="page-item disabled">
                    <a class="page-link" href="">&laquo;</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="">Last</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'store:store' %}?page={{products.next_page_number}}">&raquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{% url 'store:store' %}?page={{products.paginator.num_pages}}">Last</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<!-- Detail Modal -->
<!-- Modal -->
<div class="modal fade" id="detailModal" tabindex="-1" aria-labelledby="detail-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="detail-title"></h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-5">
                        <img class="thumbnail h-100" id="detail-image" src="" alt="" />
                    </div>
                    <div class="col-lg-6">
                        <table class="table">
                            <tr>
                                <td><strong>Description</strong></td>
                                <td>:</td>
                                <td id="detail-description"></td>
                            </tr>
                            <tr>
                                <td><strong>Price</strong></td>
                                <td>:</td>
                                <td>
                                    <h3 id="detail-price"></h3>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="detail-to-add" class="btn btn-primary update-cart" data-product=""
                    data-action="add" data-url="{% url 'store:update_item' %}">Add to Cart</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}