LiniBelajar/LiniBelajar/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('ecommerce/', include('ecommerce_app.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('about/', TemplateView.as_view(template_name='about.html')),
    path('komunitas', include('community.urls'), name='community'),
    path('kelas-online/', include('online_class.urls'), name='online_class'),
    path('talkshow/', include('event.urls'), name='event'),
    path('', include('user.urls')),
    path('', include('testvue.urls')),
    path('api/posts/', include('postAPI.urls')),
    path('api/user/', include('userAPI.urls')),
    path('api/user/profile/', include('profileAPI.urls')),
    #path('komunitas/', include('community.urls'), name='community'),
    #path('komunitas/', include('community.urls')),
    path('react/', TemplateView.as_view(template_name='react.html')),
    path('quizs', include('quiz.urls'), name='quiz'),
    path('admin/', admin.site.urls),
    #path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

LiniBelajar/community/urls.py
from . import views
from django.urls import path
from .views import *
app_name = 'community'
urlpatterns = [
    path('', PostListView.as_view(), name="community"),
    path('user/<str:username>/', UserProfileView.as_view(), name="user-profile"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('post/new/', PostCreateView.as_view(), name="post-create"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),

]

LiniBelajar/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

LiniBelajar/community/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from ckeditor.fields import RichTextField


class Post(models.Model):
    judul = models.CharField(max_length=100, blank=True)
    isi_konten = RichTextField(blank=True, null=True)
    upload_gambar = models.ImageField(upload_to='foto-post', blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.judul

    def get_absolute_url(self):
        return reverse('community:post-detail', kwargs={'pk': self.pk})

    # def upload_image(self, filename):
    #    return 'post/{}/{}'.format(self.title, filename)

    def post_save(self):
        super().post_save()

        img_post = Image.open(self.image.path)

        if img_post.height > 500 or img_post.width > 500:
            height = 500
            width = 500
            output_size = (height, width)
            img_post.thumbnail(output_size)
            img_post.post_save(self.upload_gambar.path)

LiniBelajar/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import Post
from user.models import Profile
from user.forms import RegisterUserForm, UserUpdateForm, ProfileUpdateForm


def community(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'community.html', context)

class PostListView(ListView):
    model = Post
    template_name = 'community.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']


class UserProfileView(ListView):
    model = Post
    template_name = 'post_list.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get(
            'username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['judul', 'upload_gambar', 'isi_konten']
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def post_new(request):
        if request.method == "POST":
            form = PostCreateView(request.POST, request.FILES)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['judul', 'upload_gambar', 'isi_konten']
    success_url = '/'
    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

LiniBelajar/community/templates/community/post_confirm_delete.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'nav-bar.html' %}
{% include 'message.html' %}
<div class="container card shadow border-0 p-3">
    <div class="content-section px-5">
        <form method="POST" class="mb-2 font-weight-bold">
            {% csrf_token %}
            <fieldset class="form-group text-center">
                <legend class="border-bottom mb-4">Hapus Post</legend>
                <h4>Yakin ingin menghapus post "{{ object.judul }}"</h4>
            </fieldset>
            <div class="text-center mt-4">
                <button class="btn btn-outline-danger" type="submit">Ya, Hapus</button>
                <a class="btn btn-outline-secondary" type="submit" href="{% url 'community:post-detail' object.id %}">Batalkan</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

LiniBelajar/community/templates/community/post_detail.html
{% extends 'layout.html' %}
{% block content %}
{% include 'nav-bar.html' %}
{% include 'message.html' %}
<div class="container px-4 mb-2">
<div class="card shadow-sm">
    <div class="card-header">
        <h4 class="mt-1 article-title text-center font-weight-bold">{{ post.judul }}</h4> 
    </div>
    <div class="card-body">
        {% if post.upload_gambar.url is not null %}
        <img class="img-fluid post_img rounded mx-auto d-block" width="600" src="{{ post.upload_gambar.url }}">
        {% endif %}
        <div class="px-2 text-justify">
            <p class="card-text text-justify">{{ object.isi_konten|safe }}</p>
            <article class="media content-section border-top d-flex justify-content-end mb-3">
            <img class="rounded-circle article-img mr-2 mt-2" width="20" src="{{ object.author.profile.image.url }}">
                <small class="text-muted mt-2"> oleh: <a class="mr-2" href="{% url 'community:user-profile' object.author.username %}">@{{ post.author }}</a>
                    ( {{ post.date_posted|timesince }} yang lalu )
                </small>
            </article> 
        </div>
        <div class="text-center">
            {% if object.author == user %}
            <a class="btn btn-primary btn-sm mt-1 mb-1 mr-2" href="{% url 'community:post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'community:post-delete' object.id %}">Hapus</a>
            {% endif %}
        </div>

    </div>
</div>


</div>

{% endblock content %}

LiniBelajar/community/templates/community/post_form.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'nav-bar.html' %}
{% include 'message.html' %}
<div class="container mb-5 card shadow-sm p-3">
    <div class="card-body px-2">
        <form method="POST" class="mb-2 font-weight-bold" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-5 text-center">Share Post</legend>
                {{ form.media }}
                {{ form|crispy }}
            </fieldset>
            <div class="text-center">
                <button class="btn btn-outline-info" type="submit">POST</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

LiniBelajar/community/templates/community/post_list.html
{% extends 'layout.html' %}
{% block content %}
{% include 'nav-bar.html' %}

    {% include 'message.html' %}
    <!-- <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img m-2" width="70" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h4 class="account-heading">@{{ author.username }}</h4>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <div>
            <h4>{{ view.kwargs.first_name }} {{ user.last_name }}</h4>
        </div>
    </div>
    -->
    

    
    <h5 class="text-center mb-3">Postingan oleh <span class="text-info">{{ view.kwargs.username }}</span></h5>
    {% for post in posts %}
    <div class="container card shadow border-0 pt-3 mb-1">
    
    <article class="media content-section border p-2 mb-3 pr-1">
    <img class="rounded-circle article-img mr-2" width="25" src="{{ post.author.profile.image.url }}">
        <div class="media-body pr-3">
            <div class="article-metadata">
                <div class="border-bottom mb-1">
                    <h6 class="font-weight-bold"><a class="mb-2 mt-0 article-title" href="{% url 'community:post-detail' post.id %}">{{ post.judul }}</a> <small class="text-muted">
                   ( {{ post.date_posted|timesince }} yang lalu )</small></a></h6>
                    
                </div>
                <div class="text-justify">
                    {% if post.upload_gambar.url is not null %}
                    <img class="img-fluid post_img rounded  mx-auto d-block" src="{{ post.upload_gambar.url }}">
                    {% endif %}
                    <p class="article-content">{{ post.isi_konten|safe|truncatewords:'150'|linebreaks }}<a href="{% url 'community:post-detail' post.id %}"> lebih detail...</a></p>
                </div>
            </div>
        </div>
    </article>
</div>
    {% endfor %}
{% endblock %}

LiniBelajar/community/templates/community/user_posts.html
{% extends 'layout.html' %}
{% block content %}
{% include 'nav-bar.html' %}
<div class="container">
    <h5 class="mb-3 text-center login-icon">Post oleh {{ view.kwargs.username }}</h5>
    <article class="media content-section border-bottom shadow p-3 mb-3">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                <small class="text-muted">{{ object.date_posted|timesince }} yang lalu</small></p>
                <div>
                    <h4><a class="mb-2 mt-0 article-title" href="{% url 'post-detail' post.id %}">{{ object.title }}</a></h4>
                    <p class="article-content">{{ object.content }}</p>
                </div>
            </div>
        </div>
    </article>
</div>    

{% endblock %}