LiniBelajar/LiniBelajar/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('ecommerce/', include('ecommerce_app.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('about/', TemplateView.as_view(template_name='about.html')),
    path('komunitas', include('community.urls'), name='community'),
    path('kelas-online/', include('online_class.urls'), name='online_class'),
    path('talkshow/', include('event.urls'), name='event'),
    path('', include('user.urls')),
    path('', include('testvue.urls')),
    path('api/posts/', include('postAPI.urls')),
    path('api/user/', include('userAPI.urls')),
    path('api/user/profile/', include('profileAPI.urls')),
    #path('komunitas/', include('community.urls'), name='community'),
    #path('komunitas/', include('community.urls')),
    path('react/', TemplateView.as_view(template_name='react.html')),
    path('quizs', include('quiz.urls'), name='quiz'),
    path('admin/', admin.site.urls),
    #path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

LiniBelajar/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

LiniBelajar/online_class/urls.py
from django.urls import path, include
from . import views
app_name = 'online_class'
urlpatterns = [
    path('', views.daftar_kelas, name="online_class"),
    path('pre_toefl/', views.pre_toefl_add, name="pre_toefl"),
    path('english_toddler/', views.english_todler_add, name="english_toddler"),
    path('pre_ielts/', views.pre_ielts_add, name="pre_ielts"),
    path('thanks/', views.thanks, name="thanks"),
]

LiniBelajar/online_class/models.py
from django.db import models
from django.core.validators import RegexValidator

class daftar_pre_toefl(models.Model):
    nama_lengkap=models.CharField(verbose_name="Nama Lengkap",max_length=30)
    email=models.EmailField(max_length=200)
    phone_regex = RegexValidator(regex=r'^(\+\d{1,3})?,?\s?\d{8,13}', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    #message = models.CharField(max_length = 2000, default='Saya telah mendaftar kelas')

class daftar_english_todler(models.Model):
    nama_lengkap=models.CharField(verbose_name="Nama Lengkap",max_length=30)
    email=models.EmailField(max_length=200)
    phone_regex = RegexValidator(regex=r'^(\+\d{1,3})?,?\s?\d{8,13}', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    #message = models.CharField(max_length = 2000, default='Saya telah mendaftar kelas')

class daftar_pre_ielts(models.Model):
    nama_lengkap=models.CharField(verbose_name="Nama Lengkap",max_length=30)
    email=models.EmailField(max_length=200)
    phone_regex = RegexValidator(regex=r'^(\+\d{1,3})?,?\s?\d{8,13}', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    #message = models.CharField(max_length = 2000, default='Saya telah mendaftar kelas')

LiniBelajar/online_class/forms.py
from django import forms
from .models import daftar_pre_toefl, daftar_english_todler, daftar_pre_ielts

class daftar_pre_toefl_form(forms.ModelForm):
    nama_lengkap=forms.CharField()
    email=forms.EmailField()
    phone_number = forms.CharField()
    #message = forms.CharField(widget = forms.Textarea)
    class Meta:
        model= daftar_pre_toefl
        fields=['nama_lengkap','email','phone_number',]

class daftar_english_todler_form(forms.ModelForm):
    nama_lengkap=forms.CharField()
    email=forms.EmailField()
    phone_number = forms.CharField()
    #message = forms.CharField(widget = forms.Textarea)
    class Meta:
        model= daftar_english_todler
        fields=['nama_lengkap','email','phone_number',]

class daftar_pre_ielts_form(forms.ModelForm):
    nama_lengkap=forms.CharField()
    email=forms.EmailField()
    phone_number = forms.CharField()
    #message = forms.CharField(widget = forms.Textarea)
    class Meta:
        model= daftar_pre_ielts
        fields=['nama_lengkap','email','phone_number',]

LiniBelajar/online_class/views.py
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings
from .forms import daftar_pre_toefl_form, daftar_english_todler_form, daftar_pre_ielts_form
from django.core.mail import send_mail, BadHeaderError

def daftar_kelas(request):
    return render(request, 'daftar_kelas.html')


def thanks(request):
    return render(request, 'thanks.html')


def pre_toefl_add(request):
    # if this is a POST request we need to process the form data
    form = daftar_pre_toefl_form(request.POST)
    name = request.POST.get('name', '')
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        #form = forms.daftar_pre_toefl_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('nama_lengkap')
            
            
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            #if 'english_todler' in request.POST:
            subject = "Pendaftaran Kelas Pre-TOEFL"
            body = {
            'nama_lengkap': form.cleaned_data['nama_lengkap'],
            'email': form.cleaned_data['email'],
            'phone_number': form.cleaned_data['phone_number'],
            #'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())
            
            
            messages.success(
                request, f'Halo {username}, Data anda sukses tersimpan!')
            try:
                send_mail(subject, message, 'linibelajar@gmail.com',
                        ['oktoberlin@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            
            subject2 = "Pendaftaran Kelas Pre-TOEFL berhasil!"
            email = form.cleaned_data.get('email')
            body2 = {
            'nama_lengkap': form.cleaned_data['nama_lengkap']
            }
            
            message2 = "Halo, Terima kasih telah mendaftar. Pendaftaran Kelas Pre-TOEFL anda telah berhasil. Tim kami akan segera menghubungi anda lewat Whatsapp Chat."
            try:
                send_mail(subject2, message2, settings.EMAIL_HOST_USER, [email], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            
            return redirect ("online_class:thanks")
            # register=form.save(commit=False)
            # register.nama_lengkap = request.POST.get('nama_lengkap')
            # register.email = request.POST.get('email')
            # register.phone_number = request.POST.get('phone_number')
            
            # return HttpResponseRedirect(reverse('/thanks/'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = daftar_pre_toefl_form()

    return render(request, 'pre_toefl.html', {'form': form})

def english_todler_add(request):
    # if this is a POST request we need to process the form data
    form = daftar_english_todler_form(request.POST)
    name = request.POST.get('name', '')
    if request.method == 'POST':

        # create a form instance and populate it with data from the request:
        #form = forms.daftar_pre_toefl_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('nama_lengkap')
            #form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            
            subject = "Pendaftaran Kelas English Speaking"
            body = {
            'nama_lengkap': form.cleaned_data['nama_lengkap'],
            'email': form.cleaned_data['email'],
            'phone_number': form.cleaned_data['phone_number'],
            #'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())
            
            messages.success(
                request, f'Halo {username}, Data anda sukses tersimpan!')

            try:
                send_mail(subject, message, 'linibelajar@gmail.com',
                        ['oktoberlin@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            subject2 = "Pendaftaran Kelas Speaking berhasil!"
            email = form.cleaned_data.get('email')
            body2 = {
            'nama_lengkap': form.cleaned_data['nama_lengkap']
            }
            
            message2 = "Halo, Terima kasih telah mendaftar. Pendaftaran Kelas Speaking anda telah berhasil. Tim kami akan segera menghubungi anda lewat Whatsapp Chat."
            try:
                send_mail(subject2, message2, settings.EMAIL_HOST_USER, [email], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            return redirect ("online_class:thanks")
            # register=form.save(commit=False)
            # register.nama_lengkap = request.POST.get('nama_lengkap')
            # register.email = request.POST.get('email')
            # register.phone_number = request.POST.get('phone_number')
            
            # return HttpResponseRedirect(reverse('/thanks/'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = daftar_english_todler_form()

    return render(request, 'english_toddler.html', {'form': form})


def pre_ielts_add(request):
    # if this is a POST request we need to process the form data
    form = daftar_pre_ielts_form(request.POST)
    name = request.POST.get('name', '')
    if request.method == 'POST':

        # create a form instance and populate it with data from the request:
        #form = forms.daftar_pre_toefl_form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('nama_lengkap')
            #form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            
            subject = "Pendaftaran Kelas Pre-IELTS"
            body = {
            'nama_lengkap': form.cleaned_data['nama_lengkap'],
            'email': form.cleaned_data['email'],
            'phone_number': form.cleaned_data['phone_number'],
            #'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())
            
            messages.success(
                request, f'Halo {username}, Data anda sukses tersimpan!')

            try:
                send_mail(subject, message, 'linibelajar@gmail.com',
                        ['oktoberlin@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            subject2 = "Pendaftaran Kelas Pre-IELTS berhasil!"
            email = form.cleaned_data.get('email')
            body2 = {
            'nama_lengkap': form.cleaned_data['nama_lengkap']
            }
            
            message2 = "Halo, Terima kasih telah mendaftar. Pendaftaran Kelas Pre-IELTS anda telah berhasil. Tim kami akan segera menghubungi anda lewat Whatsapp Chat."
            try:
                send_mail(subject2, message2, settings.EMAIL_HOST_USER, [email], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            return redirect ("online_class:thanks")
            # register=form.save(commit=False)
            # register.nama_lengkap = request.POST.get('nama_lengkap')
            # register.email = request.POST.get('email')
            # register.phone_number = request.POST.get('phone_number')
            
            # return HttpResponseRedirect(reverse('/thanks/'))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = daftar_pre_ielts_form()

    return render(request, 'pre_ielts.html', {'form': form})

LiniBelajar/online_class/templates/daftar_kelas.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
{% include 'nav-bar.html' %}

    <style>
      .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
}
    </style>
    
    
   <!-- 

    <div class="study mb-3">
        <img class="rounded img-fluid shadow" src="{% static 'gambar/learning-path.jpg' %}" width="1250">
    </div>
    
    <div class="shadow card mx-5 quiz-top">
        <h4 class="display-4 pt-5 text-white text-center">Fun QUIZ</h4>
        <h5 class="quiz text-center mt-2 pb-5">Tantang dirimu dengan QUIZ Sederhana ini &#128512</h5>

        <div class="text-center mt-1 mb-4">
            <button type="button" class="btn btn-sm quiz-button shadow-sm rounded line-height"><a class="nav-link counselingitem" href="{% url 'quiz' %}">Coba Quiz</a></button>
        </div>
    </div>
-->

<div class="container px-4">
  <h4 style="color:#8d54ff !important;" class="display-5 mt-4 mb-3 text-center font-weight-bold">Untuk Indonesia Merdeka Belajar</h4>
	<div class="card-deck">
        <div class="card shadow">
          <img src="{% static 'gambar/ielts.png' %}" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h4 class="card-title font-weight-bold" style="color:#8d54ff !important;">PRE-IELTS</h4>
            <p class="card-text">Kelas untuk belajar IELTS untuk pemula</p>
            <small class="card-price text-center">10x pertemuan</small>
            <h6 style="text-decoration: line-through;" class="card-price text-center font-italic text-danger mt-2">Rp.400.000</h6>
              <h5 class="card-price text-center mb-3 mt-2" style="color:#8d54ff !important;">Rp.150.000</h5>

            <div class="text-center">
              <button type="button" class="btn btn-sm counseling shadow-sm rounded line-height"><a class="nav-link counselingitem" href="{% url 'online_class:pre_ielts' %}">Daftar Sekarang</a></button>
              </div>
          </div>
        </div>
        <div class="card shadow">
          <img src="{% static 'gambar/TOEFL.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h4 class="card-title font-weight-bold" style="color:#8d54ff !important;">PRE-TOEFL</h4>
            <p class="card-text">Kelas untuk belajar TOEFL untuk pemula</p>
            <small class="card-price text-center">10x pertemuan</small>
            <h6 style="text-decoration: line-through;" class="card-price text-center font-italic text-danger mt-2">Rp.400.000</h6>
              <h5 class="card-price text-center mb-3 mt-2" style="color:#8d54ff !important;">Rp.150.000</h5>
            
            <div class="text-center">
              <button type="button" class="btn btn-sm counseling shadow-sm rounded line-height"><a class="nav-link counselingitem" href="{% url 'online_class:pre_toefl' %}">Daftar Sekarang</a></button>
              </div>
          </div>  
        </div>
        
        
        <div class="card shadow">
          <img src="{% static 'gambar/todler.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h4 class="card-title font-weight-bold" style="color:#8d54ff !important;">SPEAKING</h4>
            <p class="card-text">Kelas Speaking dimulai dari dasar</p>
            <small class="card-price text-center">10x pertemuan</small>
            <h6 style="text-decoration: line-through;" class="card-price text-center font-italic text-danger mt-2">Rp.400.000</h6>
              <h5 class="card-price text-center mb-3 mt-2" style="color:#8d54ff !important;">Rp.150.000</h5>
              
            <div class="text-center">
              <button type="button" class="btn btn-sm counseling shadow-sm rounded line-height"><a class="nav-link counselingitem" href="{% url 'online_class:english_toddler' %}">Daftar Sekarang</a></button>
              </div>
          </div>
        </div>
    </div>
</div>


 


{% endblock %}

LiniBelajar/online_class/templates/english_toddler.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
{% include 'nav-bar.html' %}
{% load crispy_forms_tags %}
<!--action="/thanks/" 
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>
-->
<div class="container card shadow border-0 pt-3">
    <div class="content-section px-5">
        <form method="post" name="english_todler" class="mb-2 font-weight-bold">
            
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Pendaftaran Kelas Speaking</legend>
                {% csrf_token %}
                {{ form|crispy }}
            </fieldset>
            <div>    
                <button type="submit" class="btn btn-outline-info mb-2">Daftar</button>
            </div>
            
        </form>
        
    </div>
</div>

{% endblock %}

LiniBelajar/online_class/templates/english_todler.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
{% include 'nav-bar.html' %}
{% load crispy_forms_tags %}
<!--action="/thanks/" 
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>
-->
<div class="container mb-5 card shadow-sm p-3">
    <div class="content-section px-5">
        <form method="post" name="english_todler" class="mb-2 font-weight-bold">
            
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Daftar Kelas English for Todler</legend>
                {% csrf_token %}
                {{ form|crispy }}
            </fieldset>
            <div>    
                <button type="submit" class="btn btn-outline-info mb-2">Daftar</button>
            </div>
            
        </form>
        
    </div>
</div>

{% endblock %}

LiniBelajar/online_class/templates/pre_ielts.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
{% include 'nav-bar.html' %}
{% load crispy_forms_tags %}
<!--action="/thanks/" 
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>
-->
<div class="container card shadow border-0 pt-3">
    <div class="content-section px-5">
        <form method="post" name="pre_ielts" class="mb-2 font-weight-bold">
            
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Daftar Kelas Pre-IELTS</legend>
                {% csrf_token %}
                {{ form|crispy }}
            </fieldset>
            <div>    
                <button type="submit" class="btn btn-outline-info mb-2">Daftar</button>
            </div>
            
        </form>
        
    </div>
</div>

{% endblock %}

LiniBelajar/online_class/templates/pre_toefl.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
{% include 'nav-bar.html' %}
{% load crispy_forms_tags %}
<!--action="/thanks/" 
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Submit</button>
</form>
-->
<div class="container card shadow border-0 pt-3">
    <div class="content-section px-5">
        <form method="post" name="pre_toefl" class="mb-2 font-weight-bold">
            
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">Daftar Kelas Pre-TOEFL</legend>
                {% csrf_token %}
                {{ form|crispy }}
            </fieldset>
            <div>    
                <button type="submit" class="btn btn-outline-info mb-2">Daftar</button>
            </div>
            
        </form>
        
    </div>
</div>

{% endblock %}

LiniBelajar/online_class/templates/thanks.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
{% include 'nav-bar.html' %}
{% include 'message.html' %}
<div class="container mb-5 p-3">
    <div class="content-section px-5 text-center">
            
            <h5>Terimakasih sudah mendaftar di linibelajar.com.</h5>
            <h5>Silahkan menunggu chat whatsapp dari Tim kami.</h5>
    </div>
</div>
{% endblock %}