LiniBelajar/LiniBelajar/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('ecommerce/', include('ecommerce_app.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('about/', TemplateView.as_view(template_name='about.html')),
    path('komunitas', include('community.urls'), name='community'),
    path('kelas-online/', include('online_class.urls'), name='online_class'),
    path('talkshow/', include('event.urls'), name='event'),
    path('', include('user.urls')),
    path('', include('testvue.urls')),
    path('api/posts/', include('postAPI.urls')),
    path('api/user/', include('userAPI.urls')),
    path('api/user/profile/', include('profileAPI.urls')),
    #path('komunitas/', include('community.urls'), name='community'),
    #path('komunitas/', include('community.urls')),
    path('react/', TemplateView.as_view(template_name='react.html')),
    path('quizs', include('quiz.urls'), name='quiz'),
    path('admin/', admin.site.urls),
    #path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

LiniBelajar/community/urls.py
from . import views
from django.urls import path
from .views import *
app_name = 'community'
urlpatterns = [
    path('', PostListView.as_view(), name="community"),
    path('user/<str:username>/', UserProfileView.as_view(), name="user-profile"),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('post/new/', PostCreateView.as_view(), name="post-create"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),

]

LiniBelajar/ecommerce_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:product_id>/<slug:product_slug>/',
        views.show_product, name='product_detail'),
    path('cart/', views.show_cart, name='show_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
]

LiniBelajar/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
]

LiniBelajar/online_class/urls.py
from django.urls import path, include
from . import views
app_name = 'online_class'
urlpatterns = [
    path('', views.daftar_kelas, name="online_class"),
    path('pre_toefl/', views.pre_toefl_add, name="pre_toefl"),
    path('english_toddler/', views.english_todler_add, name="english_toddler"),
    path('pre_ielts/', views.pre_ielts_add, name="pre_ielts"),
    path('thanks/', views.thanks, name="thanks"),
]

LiniBelajar/user/urls.py
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
   path('register/', views.registerPage, name="register"),
   path('login/', views.loginPage, name="login"),
   path('logout/', views.logoutUser, name="logout"),
   path('activate/<uidb64>/<token>/',views.activate, name='activate'),
]

LiniBelajar/ecommerce_app/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=191)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to='products_images/', blank=True)

    def __str__(self):
        return self.name


class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)

    def __str__(self):
        return "{}:{}".format(self.product.name, self.id)

    def update_quantity(self, quantity):
        self.quantity = self.quantity + quantity
        self.save()

    def total_cost(self):
        return self.quantity * self.price


class Order(models.Model):
    name = models.CharField(max_length=191)
    email = models.EmailField()
    postal_code = models.IntegerField()
    address = models.CharField(max_length=191)
    date = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return "{}:{}".format(self.id, self.email)

    def total_cost(self):
        return sum([ li.cost() for li in self.lineitem_set.all() ] )


class LineItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}:{}".format(self.product.name, self.id)

    def cost(self):
        return self.price * self.quantity

LiniBelajar/ecommerce_app/forms.py
from django import forms
from .models import Order


class CartForm(forms.Form):
    quantity = forms.IntegerField(initial='1')
    product_id = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(CartForm, self).__init__(*args, **kwargs)


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('paid',)

        widgets = {
            'address': forms.Textarea(attrs={'row': 5, 'col': 8}),
        }

LiniBelajar/ecommerce_app/views.py
from django.shortcuts import render, HttpResponse, redirect, \
    get_object_or_404, reverse
from django.contrib import messages
from django.contrib import messages
from django.conf import settings
from decimal import Decimal
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from .models import Product, Order, LineItem
from .forms import CartForm, CheckoutForm
from . import cart

# Create your views here.


def index(request):
    all_products = Product.objects.all()
    return render(request, "index.html", {
                                    'all_products': all_products,
                                    })


def show_product(request, product_id, product_slug):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = CartForm(request, request.POST)
        if form.is_valid():
            request.form_data = form.cleaned_data
            cart.add_item_to_cart(request)
            return redirect('show_cart')

    form = CartForm(request, initial={'product_id': product.id})
    return render(request, 'product_detail.html', {
                                            'product': product,
                                            'form': form,
                                            })


def show_cart(request):

    if request.method == 'POST':
        if request.POST.get('submit') == 'Update':
            cart.update_item(request)
        if request.POST.get('submit') == 'Remove':
            cart.remove_item(request)

    cart_items = cart.get_all_cart_items(request)
    cart_subtotal = cart.subtotal(request)
    return render(request, 'cart.html', {
                                            'cart_items': cart_items,
                                            'cart_subtotal': cart_subtotal,
                                            })


def checkout(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            o = Order(
                name = cleaned_data.get('name'),
                email = cleaned_data.get('email'),
                postal_code = cleaned_data.get('postal_code'),
                address = cleaned_data.get('address'),
            )
            o.save()

            all_items = cart.get_all_cart_items(request)
            for cart_item in all_items:
                li = LineItem(
                    product_id = cart_item.product_id,
                    price = cart_item.price,
                    quantity = cart_item.quantity,
                    order_id = o.id
                )

                li.save()

            cart.clear(request)

            request.session['order_id'] = o.id

            return redirect('process_payment')


    else:
        form = CheckoutForm()
        return render(request, 'checkout.html', locals())

def process_payment(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    host = request.get_host()

    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': '%.2f' % order.total_cost().quantize(
            Decimal('.01')),
        'item_name': 'Order {}'.format(order.id),
        'invoice': str(order.id),
        'currency_code': 'USD',
        'notify_url': 'http://{}{}'.format(host,
                                           reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,
                                           reverse('payment_done')),
        'cancel_return': 'http://{}{}'.format(host,
                                              reverse('payment_cancelled')),
    }

    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request, 'process_payment.html', {'order': order, 'form': form})

@csrf_exempt
def payment_done(request):
    return render(request, 'payment_done.html')


@csrf_exempt
def payment_canceled(request):
    return render(request, 'payment_cancelled.html')

LiniBelajar/ecommerce_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}?v={38}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
    crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,700,900" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}?v={1}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}?v={1}">
    <link rel="stylesheet" href="{% static 'css/templatemo-softy-pinko.css' %}?v={2}">
    <title>{% block title %}{% endblock %}Simple ecommerce </title>
    <style>
        table{
            border-collapse: collapse;
            border: none;
        }
        td{
            padding: 10px;
        }
        form{
            margin-bottom: 0;
        }
    </style>
</head>
<body>

<p>
    <a href="{% url 'index' %}">All Products</a> |
    <a href="{% url 'show_cart' %}">Cart: {{ cart_item_count }} item</a>
</p>

{% block content %}
        {% endblock content %}
        <!--<button onclick="myFunction()">Click me</button>

        <p id="demo"></p>
    <script src="{% static 'js/home.js' %}"></script>
        -->
	
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

LiniBelajar/ecommerce_app/templates/cart.html
{% extends 'base.html' %}
{% block title %}
    My Cart |
{% endblock %}
{% load static %}
{% include 'nav-bar.html' %}

{% block content %}

    <h2>My Cart</h2>
    
    {% if cart_item_count %}
    <table>
        <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th></th>
            <th></th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart_items %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.price }}</td>
                <td>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="text" name="quantity" value="{{ item.quantity }}">
                        <input type="hidden" name="item_id" value="{{ item.id }}">
                </td>
                <td>
                        <input type="submit" name="submit" value="Update">
                    </form>
                </td>
                <td>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="item_id" value="{{ item.id }}">
                        <input type="submit" name="submit" value="Remove">
                    </form>
                </td>
                <td>${{ item.total_cost }}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align: right">Total</td>
                <td>${{ cart_subtotal }}</td>
            </tr>
            <tr>
                <td></td>
                <td colspan="4" style="text-align: right">
                    <a href="{% url 'index' %}" class="btn btn-primary">Continue Shopping</a>
                </td>
                {% if cart_item_count %}
                    <td><a href="{% url 'checkout' %}" class="btn btn-primary">Checkout</a></td>
                {% endif %}
            </tr>
        </tfoot>
    </table>
    {% else %}
        <p>Cart Empty</p>
    {% endif %}


{% endblock %}

LiniBelajar/ecommerce_app/templates/checkout.html
{% extends 'base.html' %}
{% block title %}
    Checkout |
{% endblock %}
{% load static %}
{% include 'nav-bar.html' %}
{% block content %}

    <div class="container">
        <div class="row">

            <h2>Checkout</h2>

            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}


            <form action="" method="post">
                <table>
                    {% csrf_token %}
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Place Order"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

{% endblock %}

LiniBelajar/ecommerce_app/templates/index.html
{% extends 'base.html' %}
{% block title %}
    Ecommerce |
{% endblock %}
{% load static %}
{% include 'nav-bar.html' %}
{% block content %}

    <div class="container">
        <div class="row">
            <h2>Available Products</h2>

            {% for product in all_products %}
                <div class="col-lg-4">
                    <h3><a href="{% url 'product_detail' product.pk product.slug %}">{{ product.name }}</a></h3>
                    <p>Price ${{ product.price }}</p>
                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

LiniBelajar/ecommerce_app/templates/nav-bar.html
{% load static %}

    <nav class="navbar navbar-expand-sm mynav shadow-sm">
        <a class="navbar-brand mr-3" href="{% url 'home:home' %}">
            <img class="img-fluid logo" src="{% static 'gambar/logo-nav.png' %}" width="140" alt="linibelajar">
        </a>

        
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav ">
                
                <li class="nav-item active ml-auto mb-1">
                    <a class="nav-link free-class-nav font-weight-bold rounded ml-auto mr-2 px-2" href="{% url 'community:community' %}" type="button">Join Komunitas</a>
                </li>
                <li class="nav-item active ml-auto mb-1">
                    <a class="nav-link free-class-nav font-weight-bold rounded ml-auto mr-2 px-2" href="{% url 'online_class:online_class' %}" type="button">Kelas Online</a>
                </li>
                {% if user.is_authenticated %}
                
                <li class="nav-item active ml-auto mb-1">
                    <a class="nav-link shadow-sm free-class-nav font-weight-bold rounded ml-auto mr-2 px-2" href="{% url 'profile' %}"><i class="fas fa-user"></i> Profil</a>
                </li>

                <li class="nav-item active ml-auto mb-1">
                    <a class="nav-link shadow-sm free-class-nav font-weight-bold rounded ml-auto mr-2 px-2" href="{% url 'user:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </li>
                {% else %}
                <li class="nav-item active ml-auto mb-1">
                    <a class="nav-link free-class-nav font-weight-bold rounded ml-auto mr-2 px-2" href="{% url 'user:login' %}" type="button"><i class="fas fa-sign-in-alt"></i> Login</a>
                    
                </li>
                
                    
                {% endif %}


                
            </ul>
        </div>
    </nav>
 

LiniBelajar/ecommerce_app/templates/payment_cancelled.html
{% extends 'base.html' %}
{% block title %}Make Payment{% endblock %}
{% load static %}
{% include 'nav-bar.html' %}
{% block content %}
  <div>
    <p>Pembayaran gagal</p>
  </div>

{% endblock %}

LiniBelajar/ecommerce_app/templates/payment_done.html
{% extends 'base.html' %}
{% block title %}Make Payment{% endblock %}
{% load static %}
{% include 'nav-bar.html' %}
{% block content %}
  <div>
    <p>Pembayaran berhasil</p>
  </div>

{% endblock %}

LiniBelajar/ecommerce_app/templates/paypal_form.html
{% extends 'base.html' %}
{% block title %}Make Payment{% endblock %}
{% load static %}
{% include 'nav-bar.html' %}
{% block content %}
  <div>
    <h4>Pay with PayPal</h4>
    {{ form.render }}
  </div>

{% endblock %}

LiniBelajar/ecommerce_app/templates/process_payment.html
{% extends 'base.html' %}

{% block title %}Make Payment{% endblock %}

{% block content %}
    <h4>Pay with PayPal</h4>
    {{ form.render }}
{% endblock %}

LiniBelajar/ecommerce_app/templates/product_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ product.name }} |
{% endblock %}
{% load static %}
{% include 'nav-bar.html' %}

{% block content %}

    <div class="container">
        <div class="row">

            <p><a href="{% url 'index' %}">All Products </a> &gt;
                {{ product.name }}
            </p>

                <h2>{{ product.name }}</h2>
                <p>Price ${{ product.price }}</p>

                <form action="{% url 'product_detail' product.id product.slug %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Add to cart" class="btn btn-primary" >
                </form>

        </div>

    </div>

{% endblock %}